#DValues for production environment
NAMESPACE: prod
FDK_MONGODB_VOLUMENAME_DB: fdk-prod-mongodb-db
FDK_MONGODB_VOLUMENAME_BKP: fdk-prod-mongodb-bkp
FDK_MONGODB_STORAGESIZE_DB: "7G"
FDK_MONGODB_STORAGESIZE_BKP: "7G"