#DValues for staging environment
NAMESPACE: staging
FDK_MONGODB_VOLUMENAME_DB: fdk-dev-staging-mongodb-db
FDK_MONGODB_VOLUMENAME_BKP: fdk-dev-staging-mongodb-bkp
FDK_MONGODB_STORAGESIZE_DB: "7G"
FDK_MONGODB_STORAGESIZE_BKP: "7G"