apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    records.service: nginx-records
  name: nginx-records
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      records.service: nginx-records
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        records.service: nginx-records
    spec:
      containers:
        - image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
          imagePullPolicy: Always
          name: nginx-records
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ required "Missing value NGINX_RECORDS_MEMORY" .Values.NGINX_RECORDS_MEMORY | quote }}
      restartPolicy: Always
status: {}