apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    records.service: nginx-records
  name: nginx-records
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    records.service: nginx-records
status:
  loadBalancer: {}