kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  creationTimestamp: null
  labels:
    fdk.service: mongodb-claim0
  name: mongodb-claim0
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  volumeName: {{ required "Missing value FDK_MONGODB_VOLUMENAME_DB" .Values.FDK_MONGODB_VOLUMENAME_DB }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "Missing value FDK_MONGODB_STORAGESIZE_DB" .Values.FDK_MONGODB_STORAGESIZE_DB }}
status: {}

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ required "Missing value FDK_MONGODB_VOLUMENAME_DB" .Values.FDK_MONGODB_VOLUMENAME_DB }}
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  storageClassName: ""
  capacity:
    storage: {{ required "Missing value FDK_MONGODB_STORAGESIZE_DB" .Values.FDK_MONGODB_STORAGESIZE_DB }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ required "Missing value FDK_MONGODB_VOLUMENAME_DB" .Values.FDK_MONGODB_VOLUMENAME_DB }}
    fsType: ext4
