apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    records.service: records-of-processing-activities-gui
  name: records-of-processing-activities-gui
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    records.service: records-of-processing-activities-gui
status:
  loadBalancer: {}
